import path from 'path';
import fs from 'fs';
import webpack from 'webpack';
import merge from 'webpack-merge';
import HtmlWebpackPlugin from 'html-webpack-plugin';
import cheerio from 'cheerio';

import config from '../../config';
import prodConfig from './config.client.prod';
import devConfig from './config.client.dev';

const DEV = process.env.NODE_ENV !== 'production';

const baseConfig = {
	target: 'web',
	context: process.cwd(),
	entry: [
		'react-hot-loader/patch',
		// disable until 404 will be fixed
		// 'webpack-dev-server/client',
		'webpack-hot-middleware/client',
		'./client/index.js',
	],
	output: {
		path: path.resolve(process.cwd(), 'build/client'),
		publicPath: '/',
		filename: '[name].[hash].js',
		devtoolModuleFilenameTemplate: 'webpack:///[absolute-resource-path]',
	},
	devtool: 'source-map',
	module: {
		loaders: [
			{
				test: /\.js$/,
				loader: 'babel-loader',
				exclude: /node_modules/,
				query: {
					babelrc: false,
					presets: [
						'react',
						'stage-3',
						['latest', { es2015: { modules: false } }],
					],
					plugins: [
						['import', { libraryName: 'antd', style: true }],
						'react-hot-loader/babel',
						'transform-react-jsx-self',
						'transform-react-jsx-source',
						[
							'react-css-modules',
							{
								webpackHotModuleReloading: true,
								exclude: 'node_modules',
								generateScopedName: '[path]___[name]__[local]___[hash:base64:5]'
							}
						]
					],
				},
			},
			{
				test: /\.css$/,
				use: [
					{ loader: 'style-loader' },
					{
						loader: 'css-loader',
						options: {
							modules: true,
							importLoaders: 1,
							localIdentName: '[path]___[name]__[local]___[hash:base64:5]'
						}
					},
					{
						loader: 'postcss-loader',
						options: {
							sourceMap: 'inline',
							plugins: [
								require('postcss-cssnext')({
									features: {
										customProperties: {
											variables: {
												'primary-color': config.primaryColor
											}
										}
									}
								}),
								require('postcss-reporter')(),
							]
						}
					}
				]
			},
			{
				test: /\.less$/,
				use: [{
					loader: 'style-loader'
				}, {
					loader: 'css-loader'
				}, {
					loader: 'less-loader',
					options: {
						modifyVars: {
							'primary-color': config.primaryColor
						}
					}
				}]
			},
			{
				test: /\.(graphql|gql)$/,
				exclude: /node_modules/,
				loader: 'graphql-tag/loader'
			}
		],
	},
	plugins: [
		new webpack.HotModuleReplacementPlugin(),
		new webpack.NamedModulesPlugin(),
		new HtmlWebpackPlugin({
			inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
			templateContent: getHtmlTemplate(), // eslint-disable-line no-use-before-define
		}),
	],
};

function getHtmlTemplate() {
	const html = fs.readFileSync(
		path.resolve(process.cwd(), 'client/index.html')
	).toString();

	return html;
}

const currentConfig = DEV ? devConfig : prodConfig;

export default merge(baseConfig, currentConfig);
